"""SQLite / PostgreSQL session store. Schema is kept compatible across both."""
from __future__ import annotations

import json
import sqlite3
import threading
from contextlib import contextmanager
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Iterator

from backend.config import get_settings

SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    session_date TEXT PRIMARY KEY,
    phase TEXT NOT NULL,
    started_at TEXT,
    finalized_at TEXT,
    notes TEXT
);
CREATE TABLE IF NOT EXISTS ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    instrument TEXT NOT NULL,
    ltp REAL,
    volume INTEGER,
    oi INTEGER,
    bid REAL,
    ask REAL
);
CREATE INDEX IF NOT EXISTS idx_ticks_inst_ts ON ticks(instrument, ts);
CREATE TABLE IF NOT EXISTS candles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    instrument TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    open REAL, high REAL, low REAL, close REAL, volume INTEGER,
    UNIQUE(instrument, timeframe, ts)
);
CREATE INDEX IF NOT EXISTS idx_candles_inst_ts ON candles(instrument, timeframe, ts);
CREATE TABLE IF NOT EXISTS option_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS oi_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS cvd_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pcr_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    signal_id TEXT UNIQUE,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS signal_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    signal_id TEXT NOT NULL,
    state TEXT NOT NULL,
    note TEXT
);
CREATE TABLE IF NOT EXISTS ict_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS market_regime (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    regime TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    source TEXT,
    headline TEXT,
    sentiment TEXT,
    relevance REAL,
    impact TEXT,
    confidence REAL,
    payload TEXT
);
CREATE TABLE IF NOT EXISTS system_health (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS paper_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    outcome TEXT,
    move_pts REAL,
    payload TEXT NOT NULL
);
"""


class Store:
    def __init__(self, url: str | None = None):
        self.url = url or get_settings().database_url
        self._lock = threading.Lock()
        self._pg = None
        self._sqlite: sqlite3.Connection | None = None
        self._connect()
        self.init_schema()

    def _connect(self) -> None:
        if self.url.startswith("postgres"):
            import psycopg
            self._pg = psycopg.connect(self.url, autocommit=True)
            return
        path = self.url.replace("sqlite:///", "")
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self._sqlite = sqlite3.connect(path, check_same_thread=False)
        self._sqlite.row_factory = sqlite3.Row

    def init_schema(self) -> None:
        sql = SCHEMA
        if self._pg is not None:
            sql = sql.replace(
                "INTEGER PRIMARY KEY AUTOINCREMENT",
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            )
        with self._lock:
            if self._sqlite is not None:
                self._sqlite.executescript(sql)
                self._sqlite.commit()
            else:
                with self._pg.cursor() as cur:
                    for stmt in sql.split(";"):
                        s = stmt.strip()
                        if s:
                            try:
                                cur.execute(s)
                            except Exception:
                                pass

    @contextmanager
    def cursor(self) -> Iterator[Any]:
        with self._lock:
            if self._sqlite is not None:
                cur = self._sqlite.cursor()
                try:
                    yield cur
                    self._sqlite.commit()
                finally:
                    cur.close()
            else:
                cur = self._pg.cursor()
                try:
                    yield cur
                finally:
                    cur.close()

    def execute(self, sql: str, params: tuple = ()) -> None:
        sql = sql.replace("?", "%s") if self._pg is not None else sql
        with self.cursor() as cur:
            cur.execute(sql, params)

    def query(self, sql: str, params: tuple = ()) -> list[dict]:
        sql = sql.replace("?", "%s") if self._pg is not None else sql
        with self.cursor() as cur:
            cur.execute(sql, params)
            rows = cur.fetchall()
            if self._sqlite is not None:
                return [dict(r) for r in rows]
            cols = [d.name for d in cur.description] if cur.description else []
            return [dict(zip(cols, r)) for r in rows]

    def insert_json(self, table: str, ts: str, payload: dict, extra: dict | None = None) -> None:
        body = json.dumps(payload, default=str)
        if extra:
            cols = ["ts"] + list(extra.keys()) + ["payload"]
            vals = [ts] + list(extra.values()) + [body]
        else:
            cols = ["ts", "payload"]
            vals = [ts, body]
        placeholders = ",".join(["?"] * len(cols))
        self.execute(
            f"INSERT INTO {table} ({','.join(cols)}) VALUES ({placeholders})",
            tuple(vals),
        )

    def latest(self, table: str) -> dict | None:
        rows = self.query(f"SELECT * FROM {table} ORDER BY id DESC LIMIT 1")
        if not rows:
            return None
        row = rows[0]
        if "payload" in row and isinstance(row["payload"], str):
            try:
                row["payload"] = json.loads(row["payload"])
            except json.JSONDecodeError:
                pass
        return row

    def replay(self, table: str, since: str) -> list[dict]:
        rows = self.query(f"SELECT * FROM {table} WHERE ts >= ? ORDER BY ts ASC", (since,))
        out = []
        for row in rows:
            if "payload" in row and isinstance(row["payload"], str):
                try:
                    row["payload"] = json.loads(row["payload"])
                except json.JSONDecodeError:
                    pass
            out.append(row)
        return out

    def upsert_session(self, session_date: str, phase: str, **kwargs: Any) -> None:
        existing = self.query(
            "SELECT session_date FROM sessions WHERE session_date = ?",
            (session_date,),
        )
        if existing:
            sets = ["phase = ?"]
            params: list[Any] = [phase]
            for k, v in kwargs.items():
                sets.append(f"{k} = ?")
                params.append(v)
            params.append(session_date)
            self.execute(
                f"UPDATE sessions SET {', '.join(sets)} WHERE session_date = ?",
                tuple(params),
            )
        else:
            self.execute(
                "INSERT INTO sessions (session_date, phase, started_at) VALUES (?,?,?)",
                (
                    session_date,
                    phase,
                    kwargs.get("started_at") or datetime.utcnow().isoformat(),
                ),
            )

    def insert_candle(self, ts: str, instrument: str, timeframe: str, o: float, h: float, l: float, c: float, v: int) -> None:
        try:
            self.execute(
                "INSERT INTO candles (ts, instrument, timeframe, open, high, low, close, volume) VALUES (?,?,?,?,?,?,?,?)",
                (ts, instrument, timeframe, o, h, l, c, v),
            )
        except Exception:
            pass

    def upsert_signal(self, ts: str, signal_id: str, payload: str) -> None:
        existing = self.query("SELECT id FROM signals WHERE signal_id = ?", (signal_id,))
        if existing:
            self.execute("UPDATE signals SET ts = ?, payload = ? WHERE signal_id = ?", (ts, payload, signal_id))
        else:
            self.execute(
                "INSERT INTO signals (ts, signal_id, payload) VALUES (?,?,?)",
                (ts, signal_id, payload),
            )

    def archive_old_ticks(self, days: int, dest: Path) -> int:
        cutoff = (datetime.utcnow() - timedelta(days=days)).isoformat()
        rows = self.query("SELECT * FROM ticks WHERE ts < ?", (cutoff,))
        if not rows:
            return 0
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(json.dumps(rows, default=str), encoding="utf-8")
        self.execute("DELETE FROM ticks WHERE ts < ?", (cutoff,))
        return len(rows)


_store: Store | None = None


def get_store() -> Store:
    global _store
    if _store is None:
        _store = Store()
    return _store


def reset_store_for_tests(url: str) -> Store:
    global _store
    _store = Store(url)
    return _store
